# Generated by Django 5.2.14 on 2026-06-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Groupe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=120, unique=True, verbose_name="nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, default="", verbose_name="adresse"),
                ),
            ],
            options={
                "verbose_name": "groupe",
                "verbose_name_plural": "groupes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enfants",
                        to="inventree_location.categorie",
                        verbose_name="catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="référence"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "quantite_totale",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité totale"
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        default="piece", max_length=20, verbose_name="unité"
                    ),
                ),
                (
                    "valeur_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="valeur unitaire",
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="photo"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="inventree_location.categorie",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="inventree_location.groupe",
                        verbose_name="groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="LigneReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "quantite_demandee",
                    models.PositiveIntegerField(verbose_name="quantité demandée"),
                ),
                (
                    "quantite_livree",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité livrée"
                    ),
                ),
                (
                    "quantite_retournee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité retournée"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_reservation",
                        to="inventree_location.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de réservation",
                "verbose_name_plural": "lignes de réservation",
                "ordering": ["reservation", "article"],
            },
        ),
        migrations.CreateModel(
            name="Manifestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                ("date_debut", models.DateTimeField(verbose_name="date de début")),
                ("date_fin", models.DateTimeField(verbose_name="date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifestations",
                        to="inventree_location.groupe",
                        verbose_name="groupe",
                    ),
                ),
                (
                    "organisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifestations_organisees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="organisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "manifestation",
                "verbose_name_plural": "manifestations",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Mouvement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("sortie", "Sortie"),
                            ("retour", "Retour"),
                            ("perte", "Perte"),
                            ("reparation", "Réparation"),
                            ("ajustement", "Ajustement"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="quantité")),
                ("date", models.DateTimeField(verbose_name="date")),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="inventree_location.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "ligne_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="inventree_location.lignereservation",
                        verbose_name="ligne de réservation",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement",
                "verbose_name_plural": "mouvements",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                ("date_debut", models.DateTimeField(verbose_name="date de début")),
                ("date_fin", models.DateTimeField(verbose_name="date de fin")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "manifestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestations",
                        to="inventree_location.manifestation",
                        verbose_name="manifestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "prestation",
                "verbose_name_plural": "prestations",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "adresse",
                    models.TextField(blank=True, default="", verbose_name="adresse"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "capacite",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="capacité"
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lieux",
                        to="inventree_location.prestation",
                        verbose_name="prestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "lieu",
                "verbose_name_plural": "lieux",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="avatar"
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="inventree_location.groupe",
                        verbose_name="groupe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("soumise", "Soumise"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("livree", "Livrée"),
                            ("retournee", "Retournée"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("date_demande", models.DateTimeField(verbose_name="date de demande")),
                (
                    "date_retrait_prevue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retrait prévue"
                    ),
                ),
                (
                    "date_retour_prevue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retour prévue"
                    ),
                ),
                (
                    "date_retrait_reelle",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retrait réelle"
                    ),
                ),
                (
                    "date_retour_reelle",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retour réelle"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_demandees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventree_location.prestation",
                        verbose_name="prestation",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "réservation",
                "verbose_name_plural": "réservations",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.AddField(
            model_name="lignereservation",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="inventree_location.reservation",
                verbose_name="réservation",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignereservation",
            constraint=models.UniqueConstraint(
                fields=("reservation", "article"), name="unique_reservation_article"
            ),
        ),
    ]
