# Generated by Django 5.2.15 on 2026-06-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("part", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Groupe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=120, unique=True, verbose_name="nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, default="", verbose_name="adresse"),
                ),
            ],
            options={
                "verbose_name": "groupe",
                "verbose_name_plural": "groupes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Manifestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                ("date_debut", models.DateTimeField(verbose_name="date de début")),
                ("date_fin", models.DateTimeField(verbose_name="date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifestations",
                        to="inventree_location.groupe",
                        verbose_name="groupe",
                    ),
                ),
                (
                    "organisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifestations_organisees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="organisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "manifestation",
                "verbose_name_plural": "manifestations",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                ("date_debut", models.DateTimeField(verbose_name="date de début")),
                ("date_fin", models.DateTimeField(verbose_name="date de fin")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "manifestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestations",
                        to="inventree_location.manifestation",
                        verbose_name="manifestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "prestation",
                "verbose_name_plural": "prestations",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "adresse",
                    models.TextField(blank=True, default="", verbose_name="adresse"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "capacite",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="capacité"
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lieux",
                        to="inventree_location.prestation",
                        verbose_name="prestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "lieu",
                "verbose_name_plural": "lieux",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="avatar"
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="inventree_location.groupe",
                        verbose_name="groupe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("soumise", "Soumise"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("livree", "Livrée"),
                            ("retournee", "Retournée"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("forced", models.BooleanField(default=False, verbose_name="forcée")),
                ("date_demande", models.DateTimeField(verbose_name="date de demande")),
                (
                    "date_retrait_prevue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retrait prévue"
                    ),
                ),
                (
                    "date_retour_prevue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retour prévue"
                    ),
                ),
                (
                    "date_retrait_reelle",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retrait réelle"
                    ),
                ),
                (
                    "date_retour_reelle",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de retour réelle"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_demandees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventree_location.prestation",
                        verbose_name="prestation",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "réservation",
                "verbose_name_plural": "réservations",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="RentableItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "is_rentable",
                    models.BooleanField(default=True, verbose_name="louable"),
                ),
                (
                    "consommable",
                    models.BooleanField(default=False, verbose_name="consommable"),
                ),
                (
                    "caution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="caution",
                    ),
                ),
                (
                    "valeur_remplacement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="valeur de remplacement",
                    ),
                ),
                (
                    "seuil_alerte_bas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="seuil d'alerte bas"
                    ),
                ),
                (
                    "part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentable_info",
                        to="part.part",
                        verbose_name="part",
                    ),
                ),
            ],
            options={
                "verbose_name": "article louable",
                "verbose_name_plural": "articles louables",
                "ordering": ["part_id"],
                "indexes": [
                    models.Index(
                        fields=["is_rentable"], name="inventree_l_is_rent_f2eb17_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "quantite_demandee",
                    models.PositiveIntegerField(verbose_name="quantité demandée"),
                ),
                (
                    "quantite_livree",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité livrée"
                    ),
                ),
                (
                    "quantite_retournee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité retournée"
                    ),
                ),
                (
                    "etat_retour",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="état du retour",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ligne_reservations",
                        to="part.part",
                        verbose_name="part",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventree_location.reservation",
                        verbose_name="réservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de réservation",
                "verbose_name_plural": "lignes de réservation",
                "ordering": ["reservation", "part"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation", "part"), name="unique_reservation_part"
                    )
                ],
            },
        ),
    ]
