# Generated by Django 5.2.15 on 2026-06-26 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["date_retrait_prevue", "date_retour_prevue", "statut"],
                name="resa_periode_statut_idx",
            ),
        ),
    ]
