# Generated by Django 5.2.14 on 2026-07-04 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0004_reservation_numero_rentableitem_is_virtual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date_demande",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date de demande"
            ),
        ),
    ]
