# Generated by Django 5.2.15 on 2026-07-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0007_rentableitem_stock_total"),
        # part.Part existe dès la migration initiale de l'app native InvenTree ;
        # on épingle 0001_initial (comme la migration 0001 du plugin) pour rester
        # portable entre l'app `part` factice des tests et l'app native en prod.
        ("part", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lieu",
            name="prestation",
        ),
        migrations.AddField(
            model_name="prestation",
            name="lieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations",
                to="inventree_location.lieu",
                verbose_name="lieu",
            ),
        ),
        migrations.CreateModel(
            name="LignePrestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="commentaire"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_prestation",
                        to="part.part",
                        verbose_name="part",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_prestation",
                        to="inventree_location.prestation",
                        verbose_name="prestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de prestation",
                "verbose_name_plural": "lignes de prestation",
                "ordering": ["prestation", "part"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prestation", "part"), name="unique_prestation_part"
                    )
                ],
            },
        ),
    ]
