# Generated by Django 5.2.15 on 2026-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_location', '0008_conflict_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflicthistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
