# Generated by Django 5.2.15 on 2026-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0012_returnincident_destroyed"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignereservation",
            name="quantite_retour_casse",
            field=models.PositiveIntegerField(
                default=0, verbose_name="quantité cassée"
            ),
        ),
        migrations.AddField(
            model_name="lignereservation",
            name="quantite_retour_manquant",
            field=models.PositiveIntegerField(
                default=0, verbose_name="quantité manquante"
            ),
        ),
        migrations.AddField(
            model_name="lignereservation",
            name="quantite_retour_ok",
            field=models.PositiveIntegerField(
                default=0, verbose_name="quantité retournée OK"
            ),
        ),
    ]
