"""Tables du devis, de la tarification et de la traçabilité des modifications.

Tables seulement : aucun serializer, aucune vue, aucun écran. Trois blocs —
tarification (CDC §46, absente du catalogue qui ne portait que caution et valeur
de remplacement), devis et facture (`Devis` pointe la manifestation et rejoint
les bons en N↔M), traçabilité (`LigneReservation.etat` + `ModificationBon`, sans
lesquels la règle de facturation du CDC §88 n'est pas calculable).

`makemigrations` hors conteneur avait ajouté quatre `AlterField` sur des clés
primaires (`tests.settings` déclare `AutoField`, la prod est en `BigAutoField`)
et une dépendance vers le graphe de la doublure `tests/part/`. Les deux ont été
corrigées à la main.
"""

# Generated by Django 5.2.15 on 2026-09-09 22:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0022_livraison_assignation_et_etats"),
        # Comme toutes les migrations du plugin : on s'accroche au socle de l'app
        # `part` d'InvenTree, jamais au dernier n° en date. `makemigrations` lancé
        # hors conteneur vise le graphe de la doublure `tests/part/`, dont la
        # numérotation n'existe pas en prod : le serveur bouclait alors sur
        # NodeNotFoundError au démarrage.
        ("part", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TableRemise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=120, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "table de remise",
                "verbose_name_plural": "tables de remise",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="lignereservation",
            name="etat",
            field=models.CharField(
                choices=[
                    ("normale", "Au devis"),
                    ("hors_devis", "Hors devis"),
                    ("annulee", "Annulée"),
                ],
                default="normale",
                max_length=20,
                verbose_name="état vis-à-vis du devis",
            ),
        ),
        migrations.AddField(
            model_name="rentableitem",
            name="prix_location_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="prix de location HT",
            ),
        ),
        migrations.AddField(
            model_name="rentableitem",
            name="taux_tva",
            field=models.DecimalField(
                choices=[
                    (Decimal("20.00"), "20 % — taux normal"),
                    (Decimal("10.00"), "10 % — taux intermédiaire"),
                    (Decimal("5.50"), "5,5 % — taux réduit"),
                    (Decimal("2.10"), "2,1 % — taux particulier"),
                ],
                decimal_places=2,
                default=Decimal("20.00"),
                max_digits=5,
                verbose_name="taux de TVA",
            ),
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=30, unique=True, verbose_name="numéro"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("emis", "Émis"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_emission",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'émission"
                    ),
                ),
                (
                    "date_acceptation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'acceptation"
                    ),
                ),
                (
                    "support_acceptation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "E-mail"),
                            ("courrier", "Courrier"),
                            ("telephone", "Téléphone"),
                            ("verbal", "Verbal"),
                            ("sur_place", "Signature sur place"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="support d'acceptation",
                    ),
                ),
                (
                    "motif_refus",
                    models.TextField(
                        blank=True, default="", verbose_name="motif du refus"
                    ),
                ),
                (
                    "signataire_libelle",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="signataire",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="montant HT",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="montant TVA",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="montant TTC",
                    ),
                ),
                (
                    "bons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="devis",
                        to="inventree_location.reservation",
                        verbose_name="bons de réservation",
                    ),
                ),
                (
                    "manifestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis",
                        to="inventree_location.manifestation",
                        verbose_name="manifestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "devis",
                "verbose_name_plural": "devis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactureReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=30, unique=True, verbose_name="numéro"),
                ),
                ("date_emission", models.DateField(verbose_name="date d'émission")),
                (
                    "montant_total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="montant total HT",
                    ),
                ),
                (
                    "remise_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="remise (%)",
                    ),
                ),
                (
                    "entierement_regle",
                    models.BooleanField(
                        default=False, verbose_name="entièrement réglé"
                    ),
                ),
                (
                    "devis",
                    models.ManyToManyField(
                        related_name="factures",
                        to="inventree_location.devis",
                        verbose_name="devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture",
                "verbose_name_plural": "factures",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="LigneDevis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="quantité")),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="prix unitaire HT"
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        choices=[
                            (Decimal("20.00"), "20 % — taux normal"),
                            (Decimal("10.00"), "10 % — taux intermédiaire"),
                            (Decimal("5.50"), "5,5 % — taux réduit"),
                            (Decimal("2.10"), "2,1 % — taux particulier"),
                        ],
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        verbose_name="taux de TVA",
                    ),
                ),
                (
                    "remise_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="remise (%)",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="montant HT",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventree_location.devis",
                        verbose_name="devis",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_devis",
                        to="part.part",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de devis",
                "verbose_name_plural": "lignes de devis",
                "ordering": ["devis", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModificationBon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("telephone", "Téléphone"),
                            ("mail", "E-mail"),
                            ("verbal", "Verbal"),
                            ("courrier", "Courrier"),
                        ],
                        max_length=20,
                        verbose_name="canal de la demande",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", verbose_name="message à l'origine"
                    ),
                ),
                (
                    "etat_resultant",
                    models.CharField(
                        choices=[
                            ("normale", "Au devis"),
                            ("hors_devis", "Hors devis"),
                            ("annulee", "Annulée"),
                        ],
                        max_length=20,
                        verbose_name="état résultant de la ligne",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifications_bon",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modifications_bon",
                        to="part.part",
                        verbose_name="article",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="inventree_location.reservation",
                        verbose_name="bon de réservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "modification de bon",
                "verbose_name_plural": "modifications de bon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PalierTarif",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_min",
                    models.PositiveIntegerField(verbose_name="quantité minimale"),
                ),
                (
                    "prix_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="prix unitaire HT"
                    ),
                ),
                (
                    "rentable_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paliers_tarif",
                        to="inventree_location.rentableitem",
                        verbose_name="article louable",
                    ),
                ),
            ],
            options={
                "verbose_name": "palier de tarif",
                "verbose_name_plural": "paliers de tarif",
                "ordering": ["rentable_item", "quantite_min"],
            },
        ),
        migrations.CreateModel(
            name="PalierRemise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_min",
                    models.PositiveIntegerField(verbose_name="quantité minimale"),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="pourcentage de remise",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paliers",
                        to="inventree_location.tableremise",
                        verbose_name="table de remise",
                    ),
                ),
            ],
            options={
                "verbose_name": "palier de remise",
                "verbose_name_plural": "paliers de remise",
                "ordering": ["table", "quantite_min"],
            },
        ),
        migrations.AddField(
            model_name="rentableitem",
            name="table_remise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="inventree_location.tableremise",
                verbose_name="table de remise",
            ),
        ),
        migrations.AddIndex(
            model_name="devis",
            index=models.Index(fields=["statut"], name="devis_statut_idx"),
        ),
        migrations.AddIndex(
            model_name="devis",
            index=models.Index(
                fields=["manifestation"], name="devis_manifestation_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lignedevis",
            constraint=models.UniqueConstraint(
                fields=("devis", "part"), name="unique_ligne_devis_par_article"
            ),
        ),
        migrations.AddIndex(
            model_name="modificationbon",
            index=models.Index(fields=["reservation"], name="modif_bon_resa_idx"),
        ),
        migrations.AddConstraint(
            model_name="paliertarif",
            constraint=models.UniqueConstraint(
                fields=("rentable_item", "quantite_min"),
                name="unique_palier_tarif_par_quantite",
            ),
        ),
        migrations.AddConstraint(
            model_name="palierremise",
            constraint=models.UniqueConstraint(
                fields=("table", "quantite_min"),
                name="unique_palier_remise_par_quantite",
            ),
        ),
    ]
