"""Champs que le cahier des charges demande et que le modèle ne portait pas.

Purement additif, avec des défauts : `Prestation.statut` et
`modifie_apres_devis`, `Manifestation.couleur` et `pourcent_remise_globale`,
`Lieu.description`, `RentableItem.poids`.

`poids` est nul et non zéro : « inconnu » n'est pas « 0 kg », qui fausserait
toute somme de chargement. `couleur` vide veut dire « pas de couleur choisie ».

Les quatre `AlterField` sur des clés primaires ne changent rien en base : ces
tables ont été créées en `BigAutoField` sans que leurs modèles le déclarent, et
`makemigrations` proposait donc de les rétrograder à chaque passage. Le champ
est désormais déclaré explicitement ; cette migration enregistre l'état une
fois pour toutes. Sur PostgreSQL, le type cible étant identique, aucun SQL
n'est émis.
"""

# Generated by Django 5.2.15 on 2026-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0023_devis_tarification_et_tracabilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="lieu",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="couleur",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="couleur"
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="pourcent_remise_globale",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="remise globale (%)",
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="modifie_apres_devis",
            field=models.BooleanField(
                default=False, verbose_name="modifiée après le devis"
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("planifiee", "Planifiée"),
                    ("confirmee", "Confirmée"),
                    ("livree", "Livrée"),
                    ("cloturee", "Clôturée"),
                    ("annulee", "Annulée"),
                ],
                default="brouillon",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AddField(
            model_name="rentableitem",
            name="poids",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="poids unitaire (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="conflicthistory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="livraisonstatuslog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="returnincident",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="savticket",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
