"""Retire ce que la bascule remplace.

`Manifestation.organisateur` — le contact référent le remplace —,
`Profile.groupe` — un acteur interne n'appartient à aucun client — et
`Client.code`, que le schéma cible ne prévoit pas : l'unicité métier repose
désormais sur l'e-mail.

Le garde-fou passe **avant** les suppressions : si une manifestation avait
encore un organisateur sans contact, la reprise de `0027` aurait échoué à faire
son travail, et supprimer la colonne ferait perdre l'information. On préfère
échouer avec les pk fautives sous les yeux.

Irréversible : on ne reconstitue pas un compte à partir d'un contact, ni un code
unique une fois la contrainte tombée.
"""

# Generated by Django 5.2.15 on 2026-09-10 12:46

from django.db import migrations


def verifier_les_contacts(apps, schema_editor):
    """Aucune manifestation ne doit perdre son interlocuteur."""

    Manifestation = apps.get_model("inventree_location", "Manifestation")

    orphelines = list(
        Manifestation.objects.filter(contact__isnull=True)
        .exclude(organisateur__isnull=True)
        .values_list("pk", flat=True)[:20]
    )

    if orphelines:
        raise RuntimeError(
            "Manifestation(s) avec un organisateur mais sans contact : "
            f"{orphelines}. Rejouer la migration 0027 avant de supprimer la "
            "colonne."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_location", "0027_reprise_des_contacts"),
    ]

    operations = [
        migrations.RunPython(verifier_les_contacts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="client",
            name="code",
        ),
        migrations.RemoveField(
            model_name="manifestation",
            name="organisateur",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="groupe",
        ),
    ]
